//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.Goods_Chu = new HashSet<Goods_Chu>();
            this.Goods_Damage = new HashSet<Goods_Damage>();
        }
    
        public int Goods_ID { get; set; }
        public string Ru_Uid { get; set; }
        public string Goods_Name { get; set; }
        public string Goods_Brand { get; set; }
        public string Goods_Spec { get; set; }
        public string Goods_Type { get; set; }
        public int Goods_Number { get; set; }
        public Nullable<int> Goods_Place { get; set; }
    
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goods_Chu> Goods_Chu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goods_Damage> Goods_Damage { get; set; }
    }
}
