//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Damage
    {
        public int Damage_ID { get; set; }
        public Nullable<int> Damage_Uid { get; set; }
        public string Damage_Name { get; set; }
        public string Damage_Brand { get; set; }
        public string Damage_Spec { get; set; }
        public string Damage_Type { get; set; }
        public int Damage_Number { get; set; }
        public System.DateTime Damage_Time { get; set; }
        public int Damage_state { get; set; }
        public string Damage_Place { get; set; }
    
        public virtual Goods Goods { get; set; }
    }
}
