//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Chu
    {
        public int Chu_ID { get; set; }
        public Nullable<int> Chu_Uid { get; set; }
        public string Chu_Name { get; set; }
        public string Chu_Brand { get; set; }
        public string Chu_Spec { get; set; }
        public string Chu_Type { get; set; }
        public int Chu_Number { get; set; }
        public System.DateTime Chu_Time { get; set; }
        public int Chu_state { get; set; }
        public Nullable<int> Chu_Place { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Room Room { get; set; }
    }
}
